---

#- name: Create firewalld rule
#  copy:
#    src=usr/lib/firewalld/services/apache.xml
#    dest=/usr/lib/firewalld/services/apache.xml
#    mode=0644
#    owner=root
#    group=root

#- name: Temporary open 8080 port
#  firewalld:
#    service=apache
#    permanent=true
#    state=enabled
#    zone=public

#- debug: msg="Rule above is just for debugging. Remove it on production to close 8080 port"

#- name: Opening 8080 port
#  command: firewall-cmd --zone=public --permanent --add-service=apache

#- name: Opening 80 port 
#  command: firewall-cmd --zone=public --permanent --add-service=http

#- name: Opening 443 port 
#  command: firewall-cmd --zone=public --permanent --add-service=https

- name: Opening 80 port
  firewalld:
    service=http
    permanent=true
    state=enabled
    zone=public

- name: opening 443 port
  firewalld:
    service=https
    permanent=true
    state=enabled
    zone=public

- name: Restart firewalld
  service:
    name=firewalld
    state=restarted
