---
# tasks file for frontend

- name: Installing nginx
  yum:
    name=nginx
    state=latest

- name: Create directory for SSL certs
  file:
    path=/etc/nginx/ssl
    owner=root
    group=root
    mode=0700
    state=directory

- name: Adding nginx to autoload
  command: chkconfig nginx on


- name: Creating default vhost
  template:
    src=etc/nginx/conf.d/000-default.conf
    dest=/etc/nginx/conf.d/000-default.conf
    owner=root
    group=root
    mode=0644

- name: Copy nginx.conf
  template:
    src=etc/nginx/nginx.conf
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644

- name: Generate strong DH params
  command: openssl dhparam -out /etc/dhparams.pem 2048
    creates=/etc/dhparams.pem

