---
# tasks file for frontend
- include: first_task.yml
  when: "'frontend' in {{ group_names }}"

- include: install_nginx.yml
  when: "'frontend' in {{ group_names }}"

- include: generate_ssl.yml
  when: "'frontend' in {{ group_names }}"

- include: firewall.yml
  when: "'frontend' in {{ group_names }}"
