---

- name: Download jenkins WAR file
  get_url:
    url=https://updates.jenkins-ci.org/latest/jenkins.war
    dest=/opt/jetty/webapps/
    mode=0755
    owner=jetty
    group=jetty

- name: Copy Jenkins XML
  template:
    src=opt/jetty/webapps/jenkins.xml
    dest=/opt/jetty/webapps/jenkins.xml
    mode=0644
    owner=jetty
    group=jetty
