---
- name: Installing JAVA JDK 1.8
  yum:
    name=java-1.8.0-openjdk.x86_64
    state=present

- name: Getting Jetty
  get_url:
    url="{{ jetty_url }}"
    dest=/tmp/jetty.tar.gz

- name: Untar jetty src
  unarchive:
    src=/tmp/jetty.tar.gz
    dest=/opt/
    copy=no

- name: Rename jetty dir
  command: mv {{ jetty_original_dir }} /opt/jetty
    creates=/opt/jetty

- name: Create Jetty group
  group:
    name=jetty
    state=present

- name: Create jetty user
  user:
    name=jetty
    comment="Jetty user"
    group=jetty
    state=present
    home=/opt/jetty

- name: Set permissions on Jetty home
  command: chown jetty:jetty /opt/jetty -R

- name: Create init.d script for Jetty
  command: ln -s /opt/jetty/bin/jetty.sh /etc/init.d/jetty
    creates=/etc/init.d/jetty

- name: Add jetty to chkconfig
  command: chkconfig --add jetty 

- name: Add jetty to atuoload
  command: chkconfig jetty on

- name: Copy Jetty config
  template:
    src=etc/default/jetty
    dest=/etc/default/jetty
    owner=root
    group=root
    mode=0644

- name: Change default port to 8081
  replace:
    dest=/opt/jetty/start.ini
    regexp='^#\s+jetty.http.port=8080'
    replace='jetty.http.port=8081'
