---
- name: Checking for previous run of APT
  stat:
    path=/tmp/skip_yum
  register: yum_prev
  ignore_errors: True

- name: Running yum upgrade
  command: yum upgrade -y
    creates=/tmp/skip_yum
  when: yum_prev.stat.exists == False

- file:
    path=/tmp/skip_yum
    mode=0666
    owner=root
    group=root
    state=touch


- name: Install required tools
  yum:
    name={{ item }}
    state=latest
    update_cache=no
  with_items:
  - mc
  - vim
  - wget
  - curl
  - net-tools
  - sudo
  - mlocate
